@startuml

class Cards
{
    id
    name
    cardType
    elementType
    damage
    username
    deck
}

class User
{
    username
    name
    password
    coins
    eloValue
    bio
    image
    lostGames
    wonGames
    token
}

@enduml